/* File generated by the BNF Converter (bnfc 2.9.4). */

/************************* Compiler Front-End Test *************************/
/*                                                                         */
/*  This test will parse a file, print the abstract syntax tree, and then  */
/*  pretty-print the result.                                               */
/*                                                                         */
/***************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libgen.h>

#include "grammar/Parser.h"
//#include "grammar/Printer.h"
#include "grammar/Absyn.h"
#include "compiler_constants.h"

void usage(void) {
  printf("usage: Call with one of the following argument combinations:\n");
  printf("\t--help\t\tDisplay this help message.\n");
  printf("\t(no arguments)\tParse stdin verbosely.\n");
  printf("\t(files)\t\tParse content of files verbosely.\n");
  printf("\t-s (files)\tSilent mode. Parse content of files silently.\n");
}

void execute_expression(Exp expression) {
  switch (expression->kind) {
    case is_ExpLit:
      printf("%d\n", expression->u.explit_.integer_);
      break;
  }
}
void execute_statement(Stmt single_statement) {
  if (single_statement->kind == is_SExp) {
      execute_expression(single_statement->u.sexp_.exp_);
  }
}

void execute_statements_list(ListStmt statements) {
  // Not null
  if (statements) {
    execute_statement(statements->stmt_);

    execute_statements_list(statements->liststmt_);
  }

}
void iterate_over_program(Program program) {
  if (!program->kind == is_Prog) {
    return;
  }
    
  ListStmt statements = program->u.prog_.liststmt_;

  execute_statements_list(statements);
}

char* get_ll_filename(char* basename) {
  char* dot_occurence = strrchr(basename, '.');
  printf("XD%s\n", basename);
  // Null pointer or the same as basename pointer
  if (! dot_occurence || dot_occurence == basename) {
    return NULL;
    // Return only stdin.ll
    char* stdin_name = malloc(sizeof(char) * STDIN_STR_LEN); 
    strcpy(stdin_name, STDIN_NAME);

    return stdin_name;
  }
  else {
    int basename_len = (int) strlen(basename);
    // only the extension
    int ext_len = (int) strlen(dot_occurence + 1);
    int core_size;

    if (basename_len > ext_len) {
      core_size = basename_len - ext_len;
    }
    else {
      core_size = ext_len - basename_len;
    }

    printf("%d\n", core_size);
    char* ll_filename = malloc(((size_t) core_size)*sizeof(char) + LL_LEN);

    memcpy(ll_filename, basename, core_size);
    memcpy(ll_filename + core_size, LL_SUFF, LL_LEN);
    ll_filename[core_size + LL_LEN - 1] = '\0';

    return ll_filename;
  }
}

int main(int argc, char ** argv)
{
  FILE *input;
  Program parse_tree;
  int quiet = 0;
  char *filename = NULL;

  if (argc > 1) {
    if (strcmp(argv[1], "-s") == 0) {
      quiet = 1;
      if (argc > 2) {
        filename = argv[2];
      } else {
        input = stdin;
      }
    } else {
      filename = argv[1];
    }
  }

  if (filename) {
    input = fopen(filename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  }
  else input = stdin;
  /* The default entry point is used. For other options see Parser.h */
  parse_tree = pProgram(input);
  iterate_over_program(parse_tree);

  fclose(input);

  if (parse_tree)
  {
    
    //char* filename_without_path = basename(filename);
    // printf("%s\n", filename_without_path);
    char* new_name = get_ll_filename(filename);
    printf("%s\n", new_name);

    free_Program(parse_tree);

    free(new_name);

    return 0;
  }
  return 1;
}

